name: HTML validation

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  validation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        java: [8.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          architecture: x64
      - run: npm ci && npm i node-w3c-validator
      - run: npm run build
      - run: npx node-w3c-validator -i ./dist/**/*.html -f lint -evH
